site_name: 26-XII-Museum
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
  font:
    text: Roboto    
extra_css:
- css/main.css
- css/swiffy-slider.min.css
- "https://unpkg.com/aos@next/dist/aos.css"
extra_javascript:
- js/swiffy-slider.min.js
docs_dir: content
hooks:
- hooks.py
plugins:
- macros

